# Generated by Django 3.0.6 on 2020-05-28 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=35)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(max_length=6000)),
            ],
        ),
    ]
