# Generated by Django 3.0.6 on 2020-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_api', '0003_blogpost_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
