# Generated by Django 3.0.6 on 2020-06-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_api', '0004_blogpost_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_link',
            field=models.CharField(default='https://i.pinimg.com/originals/b1/8f/c6/b18fc66fd26b3dd5582ef9977f015398.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
