# Generated by Django 3.0.6 on 2020-06-12 04:23

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_api', '0006_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
